Command Argument Parser: libsrc/include/arguments.h File Reference
arguments.h File Reference
#include "command_types.h"
Functions
bool arguments_init (arguments_s *arguments, const char *self, int argc, const char *const *argv_arguments)
arguments_s structure initializer function.
bool arguments_prepare_parameters (arguments_s *arguments)
the arguments_s::parameters member initializer function.
void arguments_clean (arguments_s *arguments)
The arguments_s's clean function.
Detailed Description
This is the header file containg the functions to use in combination with the arguments_s structure.
Function Documentation
arguments_init()
bool arguments_init (arguments_s * arguments, const char * self, int argc, const char *const * argv_arguments)
arguments_s structure initializer function.
The initializer function for the arguments_s function.
Parameters
arguments A pointer to the arguments structure that's going to be initialized.
self The self value of of the arguments_s structure.
argc The counter of argv_arguments array.
argv_arguments The argv_arguments passed on from main() that are relevant to this arguments_s and onwards.
Returns
false when either arguments or self is NULL, otherwise true is returned.
References arguments_init().
Referenced by arguments_init().
arguments_prepare_parameters()
bool arguments_prepare_parameters (arguments_s * arguments)
the arguments_s::parameters member initializer function.
The parameter initializer function. This function prepares the parameter member of arguments by heap allocation. This allocation is always the same length as argv_arguments.
Returns
false when arguments is NULL, otherwise true.
References arguments_prepare_parameters().
Referenced by arguments_prepare_parameters().