Command Argument Parser: libsrc/include/notation.h File Reference
notation.h File Reference
#include "command_types.h"
#include <stdarg.h>
Functions
bool notation_init (notation_s *notation, const char *main_name, size_t alias_n, va_list aliases)
notation_s structure initializer function.
bool notation_set_description (notation_s *notation, const char *description)
Sets the value of the description on notation.
void notation_clean (notation_s *notation)
the cleanup function of the notation_s structure.
bool notation_has_value (const notation_s *notation, const char *value)
checks if the given value value can be found anywhere withing the passed notation.
bool notation_is_valid_flag (const char *value)
This function determines if a given name value is a valid flag value.
Detailed Description
This is the header file containg the functions to use in combination with the notation_s structure.
Function Documentation
notation_init()
bool notation_init (notation_s * notation, const char * main_name, size_t alias_n, va_list aliases)
notation_s structure initializer function.
Parameters
notation A pointer to the notation structure that's going to be initialized.
main_name The main name associated with this notation structure.
alias_n The length of the va-list aliases. Value is allowed to be 0.
aliases A va-list of const char* items with a length of alias_n.
Returns
false when notation or main_name is NULL.
false when main_name is invalid as described by notation_is_valid_flag().
false on any allocation failure, be it a call to malloc() or strdup().
true when none of the aforementioned apply.
References notation_init(), and notation_is_valid_flag().
Referenced by notation_init(), and option_set_name().
notation_set_description()
bool notation_set_description (notation_s * notation, const char * description)
Sets the value of the description on notation.
Parameters
notation The notation whose description member will be set.
description The description whose value it's going to be set with.
Returns
false when either notation or description is NULL.
false when strdup() fails. true when aforementioned do not apply.
References notation_set_description().
Referenced by notation_set_description(), and option_set_description().
notation_clean()
void notation_clean (notation_s * notation)
the cleanup function of the notation_s structure.
Parameters
notation A pointer to the structure that's going to be cleaned up.
References notation_clean().
Referenced by notation_clean().
notation_has_value()
bool notation_has_value (const notation_s * notation, const char * value)
checks if the given value value can be found anywhere withing the passed notation.
Parameters
notation The notation that's going to get checked.
value The value that's searched for in either the main_name or any of the aliases of notation.
Returns
true when value was found within notation, false otherwise.
References notation_has_value().
Referenced by notation_has_value().
notation_is_valid_flag()
bool notation_is_valid_flag (const char * value)
This function determines if a given name value is a valid flag value.
Parameters
value The string to be tested.
Returns
false when value does not begin with "-".
true when value does begin with "-"
References notation_is_valid_flag().
Referenced by notation_init(), and notation_is_valid_flag().